-- Generated by drizzle-kit, then extended with the data backfills below.
-- Existing lifecycle-created Transactions are identified by the tag used before
-- settlement provenance lived on the relation itself. Recorded occurrences gain
-- the schedule fields that were previously read through a live join.
ALTER TABLE "recurring_money_drafts" DROP CONSTRAINT "recurring_money_drafts_recurring_money_id_recurring_outgoings_id_fk";
--> statement-breakpoint
ALTER TABLE "recurring_money_draft_settlements" ADD COLUMN "provenance" text DEFAULT 'externally-created' NOT NULL;--> statement-breakpoint
UPDATE "recurring_money_draft_settlements" AS settlement
SET "provenance" = 'lifecycle-created'
FROM "transactions" AS transaction
WHERE transaction."id" = settlement."transaction_id"
  AND transaction."tags" @> '["recurring-settlement"]'::jsonb;--> statement-breakpoint
ALTER TABLE "recurring_money_drafts" ADD COLUMN "name" text;--> statement-breakpoint
ALTER TABLE "recurring_money_drafts" ADD COLUMN "rebill_mode" "rebill_mode" DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE "recurring_money_drafts" ADD COLUMN "rebill_amount" numeric(10, 2);--> statement-breakpoint
UPDATE "recurring_money_drafts" AS occurrence
SET "name" = schedule."name",
    "rebill_mode" = schedule."rebill_mode",
    "rebill_amount" = schedule."rebill_amount"
FROM "recurring_outgoings" AS schedule
WHERE schedule."id" = occurrence."recurring_money_id";--> statement-breakpoint
ALTER TABLE "recurring_money_drafts" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "recurring_money_drafts" ADD CONSTRAINT "recurring_money_drafts_recurring_money_id_recurring_outgoings_id_fk" FOREIGN KEY ("recurring_money_id") REFERENCES "public"."recurring_outgoings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_money_draft_settlements" ADD CONSTRAINT "chk_recurring_money_draft_settlements_provenance" CHECK ("recurring_money_draft_settlements"."provenance" IN ('lifecycle-created', 'externally-created'));
